### ISSUE TITLE
dependency on ruby 2

### ISSUE THREAD

**Issue by mose** [mime-types/mime-types-data#2]
Is this dependency really required ? There is a lot of gems depending on mime-types that are impacted by this new constraint.

**Comment by mose** [comment]
oh sorry I didn't see there was an issue already closed on that topic.

But it's going to be tricky for the 847 gems depending on mime-types..

**Comment by halostatue** [comment]
Yes, this dependency is required and I won’t be changing it in any case. I am opening a variety of PRs on gems to improve their support (there are a lot of gems that have `< 3` when it should be `< 4`). This is taking time.

Everyone else needs to make sure they have the appropriate configuration in their Gemfile if they are still on Ruby 1.9 (which reached EOL in February). This does suggest that RubyGems/Bundler could be improved to download the latest supported version for your version of Ruby instead of always trying to download the latest version.

**Comment by mose** [comment]
This is a perfectly valid point about bundler. It seems there is hope:
https://github.com/bundler/bundler/issues/4046

**Comment by halostatue** [comment]
Yes. I was told by twitter that 1.12 will have this fixed.
