### ISSUE TITLE
License.md is not recognized as MIT

### ISSUE THREAD

**Issue by jasonkarns** [mime-types/mime-types-data#26]
The format of the Licence.md file, while purporting to be MIT, contains preamble copyright that makes the actual license distinct from MIT. Indeed, many automated license tools do not recognize this license as MIT due to the non-standard preamble.

Would you be amenable to using the standard MIT License text for this file?

As one example, [licensee](https://github.com/licensee/licensee) (and by extension, GitHub, which leverages licensee), does not consider this licensed under MIT.

https://api.github.com/repos/mime-types/mime-types-data/license

```
license: {
  key: "other",
  name: "Other",
  spdx_id: "NOASSERTION",
  url: null,
  node_id: "MDc6TGljZW5zZTA="
}
```

Corresponding license response for rails, which is recognized as MIT: https://api.github.com/repos/rails/rails/license

```
license: {
  key: "mit",
  name: "MIT License",
  spdx_id: "MIT",
  url: "https://api.github.com/licenses/mit",
  node_id: "MDc6TGljZW5zZTEz"
}
```

I would be willing to open the PR for this, if it would be considered. Thanks!

**Comment by halostatue** [comment]
I am more interested in the human-readable format of this than machine-readable formatting. I would suggest that this is an enhancement that can or should be made to licensee’s preamble stripping.

**Comment by jasonkarns** [comment]
> I am more interested in the human-readable format of this than machine-readable formatting.

The latter has an arguably bigger impact on the ease by which companies can incorporate and leverage this library. Without being recognized (automatically) as MIT-licensed software, this library is rejected as an unacceptable dependency.

**Comment by halostatue** [comment]
The automatic acceptance of this library by users is not my problem to solve, and I will not be changing the format of `Licence.md` to make it easier for machines to recognize, as machines are not the target of licences or documentation: humans are.

As I said, the licence detection heuristics for licensee can and probably should be improved because the extra formatting that I have is pretty easily detectable as it is (a) two markdown headers for improved readability and (b) a single markdown bullet point in front of the copyright statement.

I do appreciate the request, but will not be changing my mind on this.
