### ISSUE TITLE
file.mp4 returns "application/mp4" instead of "video/mp4"

### ISSUE THREAD

**Issue by newstler** [mime-types/mime-types-data#42]
Assume it's happening because of the alphabetical order, but anyway I guess "video/mp4" should be preferred.
Also shouldn't file.m4v also return "video/x-m4v" instead of "video/vnd.objectvideo" (which according to IANA is for .mp4 also) as it's not being standardized?

**Comment by halostatue** [comment]
For the first issue, a PR to remove `.mp4` from `application/mp4` could considered, as most people would expect it to be a video file instead of an application file. The preference / priority sort is defined in `ruby-mime-types`, not in this file, but your supposition is correct that lexical order makes a difference.

The `x-` prefix has been deprecated for non-standard media types, and `video/vnd.objectvideo` _might_ be registered, but it is registered under a vendor prefix, which means much the same as `x-`. (It’s closer to the `-webkit` or `-gecko` prefixes for CSS properties, but same thing.)

**Comment by halostatue** [comment]
I would accept a PR that removes `.m4v` from `video/vnd.objectvideo` as the registration document (which is _not_ parsed by default) does not include `m4v` as a known extension.

**Comment by halostatue** [comment]
Digging deeper on `application/mp4`, it’s not _wrong_ to use `.mp4` (it’s in the registration document), and `audio/mp4` is likely to supersede `video/mp4` in any case. It’s not possible to determine whether a file labeled `.mp4` is an Audio MP4 file, a Video MP4 file, or something else without digging deeper (possibly using a magic database or something similar).

I will _not_ accept a PR removing `.mp4` from `application/mp4`; instead, your software should make decisions based on the context in which you’re expecting files to be one of the `*/mp4` types.

From RFC 4337:

```
2.  Selection of MIME Types for MP4 Files

   The MIME types to be assigned to MP4 files are selected according to
   the contents.  Basic guidelines for selecting MIME types are as
   follows:

   a) if the file contains neither visual nor audio presentations, but
      only, for example, MPEG-J or MPEG-7, use application/mp4;

   b) for all other files, including those that have MPEG-J, etc., in
      addition to video or audio streams, video/mp4 should be used;
      however:

   c) for files with audio but no visual aspect, including those that
      have MPEG-J, etc., in addition to audio streams, audio/mp4 may be
      used.

   In any case, these indicate files conforming to the "MP4"
   specification, ISO/IEC 14496-1:2000, systems file format.
```
