### ISSUE TITLE
Validity of data

### ISSUE THREAD

**Issue by ioquatix** [mime-types/mime-types-data#6]
I'm looking at the text mime types.

I see text/plain includes markdown and md as extensions, but I also see text/markdown but without any extensions listed.

http://stackoverflow.com/questions/10701983/what-is-the-mime-type-for-markdown

Is this a bug?

**Comment by ioquatix** [comment]
Another thing that strikes me as odd, is the listing of c source code under text/plain. Does that really make sense?

**Comment by halostatue** [comment]
`text/markdown` should probably include `md`, `mkd`, and `markdown` as extensions, and a pull-request would be accepted.

There’s a lot of historical data in this database, and `.c` as `text/plain` is not incorrect because it *is* just a text file as far as most systems are concerned. Even `file foo.c` can’t tell you more than it being an ASCII-encoded or UTF-8 encoded text file, and that uses “magic bytes” for detection.

**Comment by ioquatix** [comment]
There are tons of files that could be considered `text/plain`.

`cc` `c` `h` `hpp` `cpp` `c++` and about a billion others. But, if you only enumerate SOME of them in text/plain, is that sort of worse than only enumerating the main ones (e.g. perhaps only txt)

**Comment by halostatue** [comment]
Mmm. You’re right that there are an infinite number of `text/plain` extensions, but these have been in the registry since very early ([`lib/mime/types.rb:805`](https://github.com/mime-types/ruby-mime-types/blob/f1ef356dfa52eaefcf4c39995d762a9d404ca899/trunk/mime-types/lib/mime/types.rb#L805)) and in the Perl library I ported before that. I’m sure I could find which data source I used that included that as a text extension at the time, but I didn’t arbitrarily make the decision myself.

I’m not sure it’s wrong (nor sure that it’s right), but agree that it feels weird, except when you remember that we’re talking about data that originally came from Apache httpd which used extensions to determine the way that files would be sent across the wire to the browser, and the browser which would decide to download or display the data received. At some point, someone decided that `c` absolutely should be displayed in-line as text if linked to and not downloaded. (This is one of the reasons why I don’t want to make the registry immutable in the Ruby implementation, so that application developers have an opportunity to modify the types that matter to their application. This is something that probably needs to be documented better.)

**Comment by ioquatix** [comment]
Just so we are on the same page. I'm only arguing against immutability in the global context. For example right now, if I want to add a mime type to mail but not rack-static (as an imaginary example), it's not possible, if they both use the same global registry. To me, this is a poor design.

**Comment by halostatue** [comment]
To be clear: there’s nothing about the registries (for Ruby) that require that they be global. In fact, the global registry itself is implemented as an instance of `MIME::Types` itself. There are memory costs involved with maintaining multiple registries, but the design permits the use of multiple registries.
